spring:
  datasource:
    url: jdbc:mysql://localhost:3306/campus_fish?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update     # 自动建表，可改为 validate 或 none
    show-sql: true

server:
  port: 8080
